### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by kozbo** [ga4gh/ga4gh-server#1592]
Docker builds automatically from a hook into github. Upon inspecting it I find that it has been failing since we added the `protoc` requirement.
```
  Downloading ga4gh_schemas-0.0.9.tar.gz (2.1MB)

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-LbEI2c/ga4gh-schemas/setup.py", line 37, in <module>
        process_schemas.main([PROTOCOL_VERSION, 'python'])
      File "scripts/process_schemas.py", line 222, in main
        pb.run(parsedArgs)
      File "scripts/process_schemas.py", line 207, in run
        protoc = self._getProtoc(destination_path)
      File "scripts/process_schemas.py", line 169, in _getProtoc
        protocs))
    Exception: Can't find a good protoc. Tried [u'/tmp/pip-build-LbEI2c/ga4gh-schemas/python/protobuf/src/protoc']
```

**Comment by david4096** [comment]
The dockerfile needs to be updated to pull from the master branch of the schemas. Add `-c constraints.txt` on the `pip install .` line and I think it will work. It's getting an old version https://hub.docker.com/r/ga4gh/server/builds/b6trntkybmv6bqewweembkw/
