### ISSUE TITLE
installing dev-requirements gives error about _markerlib

### ISSUE THREAD

**Issue by kozbo** [ga4gh/ga4gh-server#1621]
when running 
`pip install -r dev-requirements.txt -c constraints.txt`
we have seen the fullowing error when installing the distribute component 
```
Collecting distribute
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/distribute.egg-info
    writing requirements to pip-egg-info/distribute.egg-info/requires.txt
    writing pip-egg-info/distribute.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/distribute.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/distribute.egg-info/dependency_links.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jf/kf4j1nxn0w5bt3851z_3xmj40000gn/T/pip-build-6UAui8/distribute/setup.py", line 58, in <module>
        setuptools.setup(**setup_params)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setuptools/command/egg_info.py", line 177, in run
        writer = ep.load(installer=installer)
      File "pkg_resources.py", line 2241, in load
        if require: self.require(env, installer)
      File "pkg_resources.py", line 2254, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "pkg_resources.py", line 2471, in requires
        dm = self._dep_map
      File "pkg_resources.py", line 2682, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "pkg_resources.py", line 2699, in _compute_dependencies
        from _markerlib import compile as compile_marker
    ImportError: No module named _markerlib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jf/kf4j1nxn0w5bt3851z_3xmj40000gn/T/pip-build-6UAui8/distribute/
(mar2) Kevins-MacBook-Air:kevin-ga4gh-server kosborn$ easy_install distribute
```

**Fixed by running** 
`easy_install distribute`
and then re-running 
`pip install -r dev-requirements.txt -c constraints.txt`

**Comment by kozbo** [comment]
adding this issue to document the workaround.

**Comment by david4096** [comment]
I've seen other people hit this @achave11 . We should add a pullout in the OS X docs.
