### ISSUE TITLE
Add "update example data" to release process

### ISSUE THREAD

**Issue by david4096** [ga4gh/ga4gh-server#1629]
We unfortunately missed this, it should be in the release process docs http://ga4gh-server.readthedocs.io/en/stable/development.html#release-process

**Comment by CanWood** [comment]
Not sure if this is related, but when following the [docs](https://media.readthedocs.org/pdf/ga4gh-reference-implementation/latest/ga4gh-reference-implementation.pdf), using the [example-data](https://github.com/ga4gh/ga4gh-server/releases/download/data/ga4gh-example-data_4.6.tar) fails.  SHould I follow this issue or open anew one?  Cheers!  ( output follows ):
```
(ga4gh-env) user@localhost:/srv/ga4gh$ ga4gh_server
Traceback (most recent call last):
  File "/srv/ga4gh/ga4gh-env/bin/ga4gh_server", line 11, in <module>
    sys.exit(server_main())
  File "/srv/ga4gh/ga4gh-env/local/lib/python2.7/site-packages/ga4gh/server/cli/server.py", line 51, in server_main
    parsedArgs.config_file, parsedArgs.config, parsedArgs.port)
  File "/srv/ga4gh/ga4gh-env/local/lib/python2.7/site-packages/ga4gh/server/frontend.py", line 296, in configure
    app.backend = _configure_backend(app)
  File "/srv/ga4gh/ga4gh-env/local/lib/python2.7/site-packages/ga4gh/server/frontend.py", line 259, in _configure_backend
    dataRepository.open(datarepo.MODE_READ)
  File "/srv/ga4gh/ga4gh-env/local/lib/python2.7/site-packages/ga4gh/server/datarepo.py", line 618, in open
    self.load()
  File "/srv/ga4gh/ga4gh-env/local/lib/python2.7/site-packages/ga4gh/server/datarepo.py", line 1425, in load
    self._readSystemTable()
  File "/srv/ga4gh/ga4gh-env/local/lib/python2.7/site-packages/ga4gh/server/datarepo.py", line 744, in _readSystemTable
    raise exceptions.RepoInvalidDatabaseException(self._dbFilename)
ga4gh.server.exceptions.RepoInvalidDatabaseException: Database file 'ga4gh-example-data/registry.db' is malformed.  Either change the configuration to point to a valid file or create one using the repo manager.
```
